package com.example.smartroom.modules.sensor_reading.controller;

import com.example.smartroom.core.common.vo.ApiResponseBody;
import com.example.smartroom.core.common.vo.PaginationInfo;
import com.example.smartroom.modules.sensor_reading.dto.CreateBatchSensorReadingDto;
import com.example.smartroom.modules.sensor_reading.dto.CreateSensorReadingDto;
import com.example.smartroom.modules.sensor_reading.dto.CreateSensorReadingWithoutTimestampDto;
import com.example.smartroom.modules.sensor_reading.dto.SensorReadingDto;
import com.example.smartroom.modules.sensor_reading.dto.SensorReadingStatisticsDto;
import com.example.smartroom.modules.sensor_reading.service.SensorReadingService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.List;

@RestController
@RequestMapping("/api/v1/sensor-readings")
@RequiredArgsConstructor
public class SensorReadingControllerV1 {
    private final SensorReadingService sensorReadingService;

    /**
     * Tạo một sensor reading mới (Client timestamp)
     * 
     * Request body example:
     * {
     *   "sensorId": 1,
     *   "tempC": 25.5,
     *   "volt": 220.0,
     *   "ampe": 1.5,
     *   "watt": 330.0,
     *   "wattHour": 165.0,
     *   "hz": 50.0,
     *   "powerFactor": 0.95,
     *   "timestamp": "2024-01-15T10:30:00Z"
     * }
     */
    @PostMapping
    public ResponseEntity<ApiResponseBody<SensorReadingDto>> createReading(
            @RequestBody @Valid CreateSensorReadingDto createDto) {
        SensorReadingDto result = sensorReadingService.create(createDto);
        return ResponseEntity.ok(ApiResponseBody.success("Created successfully", result));
    }

    /**
     * Tạo nhiều sensor readings (Batch Upload)
     * 
     * Request body example:
     * {
     *   "readings": [
     *     {
     *       "sensorId": 1,
     *       "tempC": 25.5,
     *       "volt": 220.0,
     *       "timestamp": "2024-01-15T10:30:00Z"
     *     },
     *     {
     *       "sensorId": 2,
     *       "tempC": 24.8,
     *       "volt": 219.5,
     *       "timestamp": "2024-01-15T10:30:00Z"
     *     }
     *   ]
     * }
     */
    @PostMapping("/batch")
    public ResponseEntity<ApiResponseBody<List<SensorReadingDto>>> createBatchReadings(
            @RequestBody @Valid CreateBatchSensorReadingDto batchDto) {
        List<SensorReadingDto> result = sensorReadingService.createBatch(batchDto);
        return ResponseEntity.ok(ApiResponseBody.success("Batch created successfully", result));
    }

    /**
     * Tạo sensor reading với server timestamp
     * 
     * Request body example:
     * {
     *   "sensorId": 1,
     *   "tempC": 25.5,
     *   "volt": 220.0,
     *   "ampe": 1.5,
     *   "watt": 330.0,
     *   "wattHour": 165.0,
     *   "hz": 50.0,
     *   "powerFactor": 0.95
     * }
     * Note: timestamp will be auto-generated by server
     */
    @PostMapping("/auto-timestamp")
    public ResponseEntity<ApiResponseBody<SensorReadingDto>> createReadingWithAutoTimestamp(
            @RequestBody @Valid CreateSensorReadingWithoutTimestampDto createDto) {
        SensorReadingDto result = sensorReadingService.createWithAutoTimestamp(createDto);
        return ResponseEntity.ok(ApiResponseBody.success("Created with auto timestamp", result));
    }

    /**
     * Lấy danh sách sensor readings với pagination
     * 
     * @param page Page number (default: 0)
     * @param size Page size (default: 20)
     * 
     * Example: GET /api/v1/sensor-readings?page=0&size=20
     */
    @GetMapping
    public ResponseEntity<ApiResponseBody<PaginationInfo<SensorReadingDto>>> getAllReadings(
            @PageableDefault(size = 20) Pageable pageable) {
        PaginationInfo<SensorReadingDto> result = sensorReadingService.getList(pageable);
        return ResponseEntity.ok(ApiResponseBody.success("Fetched successfully", result));
    }

    /**
     * Lấy sensor reading theo ID
     * 
     * Example: GET /api/v1/sensor-readings/1
     */
    @GetMapping("/{id}")
    public ResponseEntity<ApiResponseBody<SensorReadingDto>> getReadingById(@PathVariable Long id) {
        SensorReadingDto result = sensorReadingService.getById(id);
        return ResponseEntity.ok(ApiResponseBody.success("Fetched successfully", result));
    }

    /**
     * Lấy readings theo sensor ID với optional time range filtering
     * 
     * @param sensorId Sensor ID
     * @param startTime Start timestamp (optional, ISO-8601 format)
     * @param endTime End timestamp (optional, ISO-8601 format)
     * @param page Page number (default: 0)
     * @param size Page size (default: 50, or 100 if time range specified)
     * 
     * Examples:
     * - GET /api/v1/sensor-readings/sensor/1?page=0&size=50
     * - GET /api/v1/sensor-readings/sensor/1?startTime=2024-01-15T00:00:00Z&endTime=2024-01-15T23:59:59Z&page=0&size=100
     */
    @GetMapping("/sensor/{sensorId}")
    public ResponseEntity<ApiResponseBody<PaginationInfo<SensorReadingDto>>> getReadingsBySensor(
            @PathVariable Long sensorId,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant startTime,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant endTime,
            @PageableDefault(size = 50) Pageable pageable) {
        PaginationInfo<SensorReadingDto> result = sensorReadingService.getBySensorId(
            sensorId, startTime, endTime, pageable);
        return ResponseEntity.ok(ApiResponseBody.success("Fetched successfully", result));
    }

    /**
     * Lấy N readings mới nhất theo sensor ID
     * 
     * @param sensorId Sensor ID
     * @param limit Số lượng readings (default: 10)
     * 
     * Example: GET /api/v1/sensor-readings/sensor/1/latest?limit=10
     */
    @GetMapping("/sensor/{sensorId}/latest")
    public ResponseEntity<ApiResponseBody<List<SensorReadingDto>>> getLatestReadings(
            @PathVariable Long sensorId,
            @RequestParam(defaultValue = "10") int limit) {
        List<SensorReadingDto> result = sensorReadingService.getLatestBySensorId(sensorId, limit);
        return ResponseEntity.ok(ApiResponseBody.success("Fetched successfully", result));
    }

    /**
     * Lấy thống kê theo sensor ID và khoảng thời gian
     * 
     * @param sensorId Sensor ID
     * @param startTime Start timestamp (ISO-8601 format)
     * @param endTime End timestamp (ISO-8601 format)
     * 
     * Example: GET /api/v1/sensor-readings/sensor/1/statistics?startTime=2024-01-15T00:00:00Z&endTime=2024-01-15T23:59:59Z
     */
    @GetMapping("/sensor/{sensorId}/statistics")
    public ResponseEntity<ApiResponseBody<SensorReadingStatisticsDto>> getStatistics(
            @PathVariable Long sensorId,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant startTime,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant endTime) {
        SensorReadingStatisticsDto result = sensorReadingService.getStatistics(sensorId, startTime, endTime);
        return ResponseEntity.ok(ApiResponseBody.success("Statistics fetched successfully", result));
    }

    /**
     * Lấy readings theo nhiều sensor IDs và khoảng thời gian
     * 
     * Request body example:
     * {
     *   "sensorIds": [1, 2, 3],
     *   "startTime": "2024-01-15T00:00:00Z",
     *   "endTime": "2024-01-15T23:59:59Z",
     *   "page": 0,
     *   "size": 100
     * }
     */
    @PostMapping("/by-sensors")
    public ResponseEntity<ApiResponseBody<PaginationInfo<SensorReadingDto>>> getReadingsByMultipleSensors(
            @RequestBody @Valid MultipleSensorsQueryDto queryDto) {
        PaginationInfo<SensorReadingDto> result = sensorReadingService.getByMultipleSensors(
            queryDto.getSensorIds(),
            queryDto.getStartTime(),
            queryDto.getEndTime(),
            Pageable.ofSize(queryDto.getSize()).withPage(queryDto.getPage())
        );
        return ResponseEntity.ok(ApiResponseBody.success("Fetched successfully", result));
    }

    /**
     * Xóa sensor reading theo ID (Admin only)
     * 
     * Example: DELETE /api/v1/sensor-readings/1
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<ApiResponseBody<Boolean>> deleteReading(@PathVariable Long id) {
        sensorReadingService.delete(id);
        return ResponseEntity.ok(ApiResponseBody.success("Deleted successfully", true));
    }

    /**
     * Xóa readings theo sensor ID với optional time range (Admin only)
     * 
     * @param sensorId Sensor ID
     * @param startTime Start timestamp (optional, ISO-8601 format)
     * @param endTime End timestamp (optional, ISO-8601 format)
     * 
     * Examples:
     * - DELETE /api/v1/sensor-readings/sensor/1?startTime=2024-01-01T00:00:00Z&endTime=2024-01-14T23:59:59Z (delete range)
     * - DELETE /api/v1/sensor-readings/sensor/1 (delete all - use with caution!)
     */
    @DeleteMapping("/sensor/{sensorId}")
    public ResponseEntity<ApiResponseBody<Integer>> deleteReadingsBySensor(
            @PathVariable Long sensorId,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant startTime,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant endTime) {
        int deletedCount = sensorReadingService.deleteBySensorId(sensorId, startTime, endTime);
        return ResponseEntity.ok(ApiResponseBody.success("Deleted " + deletedCount + " readings", deletedCount));
    }

    /**
     * DTO for multiple sensors query
     */
    @lombok.Data
    public static class MultipleSensorsQueryDto {
        @jakarta.validation.constraints.NotEmpty(message = "Sensor IDs list cannot be empty")
        private List<Long> sensorIds;
        
        @jakarta.validation.constraints.NotNull(message = "Start time is required")
        @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
        private Instant startTime;
        
        @jakarta.validation.constraints.NotNull(message = "End time is required")
        @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
        private Instant endTime;
        
        private int page = 0;
        private int size = 100;
    }
}
